spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5434/crg_gis_service
    username: fiz
    password: 314
crg:
  datasource:
    target:
      url: jdbc:postgresql://localhost:5434/
      username: fiz
      password: 314

logging:
  file:
    name: /opt/datasets.log

server:
  port: 5649
